<?php
define('PATTERNLOG','/^[a-zA-Z][a-zA-Z0-9-_\.]{1,20}$/');
define('PATTERNPASS','/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).*$/');
define('HOST','localhost');
define('USER','root');
define('PASS','');
define('DB','avtorization');
define('','');
define('','');
?>
